name = "GenericCharacterTables"
uuid = "fdcc7804-6c20-4e83-8118-baad6b7d05b7"
authors = ["Andreas Leim <leim@rhrk.uni-kl.de>", "Martin Wagner <marwagne@rhrk.uni-kl.de>", "Max Horn <mhorn@rptu.de>"]
version = "0.7.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
AbstractAlgebra = "0.44.12"
Compat = "4.11"
Hecke = "0.35.13"
JSON = "^0.20, ^0.21"
Markdown = "1"
Oscar = "1.3"
julia = "1.6"

[extras]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
